### ISSUE TITLE
Multiple files doesn't work

### ISSUE THREAD

**Issue by OnnoPaap** [rcdmk/aspZip#3]
When I make a list of files to be zipped (in a loop) and add each file one by one (like e.g. 10 files), the resulting archive.zip file only contains 1 file.
Windows Server 2008 R2 64 bits 
Classic ASP.

snippet of my code:
dim zip
set zip = new aspZip
zip.OpenArquieve(".\archive.zip")
while not u.EOF
	filepath=u.fields("imagefilepath") & "\" & u.fields("imagefilename")
	response.write("`<br>`" & filepath)
	zip.Add(filepath)
	u.MoveNext
wend
zip.CloseArquieve()
Set zip = Nothing 

output:
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400847.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400849.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400819.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400821.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400823.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400825.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400827.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400829.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400831.pdf
Certs/100902/5-0001-A-SB1-01-FND$L9ZR100206\5400845.pdf

archive.zip only contains 1 file which is not stored with a path

**Comment by rcdmk** [comment]
Hi. I'll take a look into it.
As a workaround dor now, you can try to move all this files to a single folder and add the folder instead.

**Comment by OnnoPaap** [comment]
Your workaround suggestion did the job. Thank you. 

This aspZip class for classic asp is very important because
- The competitor xzip.dll works only in 32 bits mode. When you cannot set shared pool to allow 32 bits for another reason, it won't work.
- The alternative is a shell command e.g. to 7zip which would require the cmd.exe to be given permission to run from IUSR user, which is a big no for security reasons. 

So, thanks!

**Comment by rcdmk** [comment]
Great! Thank you for your time writing back. I can add this reasons to the README file if you don't mind. I can even add a quotation mentioning your name if you prefer.

**Comment by OnnoPaap** [comment]
rcdmk, I'm ok with you using it. Don't put my name up.

**Comment by rcdmk** [comment]
An update here, after all those years: I got version 0.4 working on Windows 11 Home with IIS Express, which should work on newer server versions as well, like 2022, which is based of Windows 10.

**Comment by OnnoPaap** [comment]
Dude! Thank you very much.

**Comment by rcdmk** [comment]
I'll close this issue with the hope that it is solved, but please feel free to reopen if the issue persists.
