### ISSUE TITLE
Zip File Access Denied

### ISSUE THREAD

**Issue by nuclearsiloman** [rcdmk/aspZip#4]
I'm excited about this Class!  I use your json one all the time.  Good stuff.

I have it creating a .zip but the resultant file seems to have limited access permission and when I try to open it in Explorer it says I do not have rights to read it.

I'm zipping up a folder, then using msxml, sending it to another server.  Is this a limitation -but- using your class will I be able to unzip it on the other server via asp?

**Comment by rcdmk** [comment]
Hi. I'm glad you liked my work.

This class has a known issue to unzip files. I've not managed to find why, but only directory structure is retrieved when unzipping with the native Windows API.

**Comment by nuclearsiloman** [comment]
So I should find another solution?  Any suggestions?

**Comment by rcdmk** [comment]
I don't know of any component free solution. You will probably have to use .net libs or run a binary as 7zip in your server.

**Comment by nuclearsiloman** [comment]
OK.  Thanks for the good work.
