### ISSUE TITLE
some zip files are missing after downloading to local system...

### ISSUE THREAD

**Issue by gchandrakanth2014** [rcdmk/aspZip#5]
some zip files are missing after downloading to local system... but all files got created on server (2008 r2). checked in multiple system download count varies..(not full count)

**Comment by rcdmk** [comment]
Hello.
I'm not sure if I understood what you said.  
You used this class to compress some files in the server and those files are uncompressed correctly in the server but not when you download the zip file and extract them locally. Is that correct?

**Comment by gchandrakanth2014** [comment]
Hi,
Partially correct! May be I did not explained it correctly.
We are using this class to zip the multiple zip files to single zip file. On server we can see that all the zip files are correctly zipped to one zip file, but in local system some zip files are missing in the main zip file after download.

**Comment by gchandrakanth2014** [comment]
Some more info.. Server is 2012 R2 and local system is 2007. Is classic asp having issue on windows server 2012 R2?

**Comment by rcdmk** [comment]
Hum... Not sure. Maybe a problem with access rights or the native compression API.
I'll have to investigate.

Thanks for the feedback.

**Comment by gchandrakanth2014** [comment]
Ok.. please let me know how we can add folder to zip. Thanks in advance.

**Comment by rcdmk** [comment]
Hi. You just have to provide a folder path to the method.

```asp
<%
' ...
zip.Add("..\src")
%>
```

**Comment by gchandrakanth2014** [comment]
Yes.. its working when i passing hard code values zip.add("D:/,,,/src")
when i am using below code empty zip folder got created

Call CreateZip(rsFiles("MFDB02_FILE_N"))

Sub CreateZip(FileName)
		set zip = new aspZip
		filepath = folderName & ".zip"
		zip.OpenArquieve("../direct/" & filepath)
		zip.add(folderpath & folderName)
		zip.CloseArquieve()
		set zip = nothing
End Sub

**Comment by rcdmk** [comment]
Thais is because you are not referencing the `FileName` parameter in the function body.
Also, the `folderpath` variable declaration is not present, so I'm assuming that it is declared elsewhere.

**Comment by preludem** [comment]
Hello. İ'm trying to use this script on windows server 2012 r2 and windows 8.1 but there is an error. I did to zip the files. However, when I click on the zip file, it does not open and gives an error. Also, I cannot delete the zipped file and move it to another location. Please help me with the error. I really need this script.

**Comment by rcdmk** [comment]
> Hello. İ'm trying to use this script on windows server 2012 r2 and windows 8.1 but there is an error. I did to zip the files. However, when I click on the zip file, it does not open and gives an error. Also, I cannot delete the zipped file and move it to another location. Please help me with the error. I really need this script.

@preludem, I've answered you in the other issue #7 you created right after commenting here.

I'll close this issue here as this is an unrelated issue that hadn't had a follow-up for a long time.
