### ISSUE TITLE
Empty zip file

### ISSUE THREAD

**Issue by GarveScott-Lodge** [rcdmk/aspZip#6]
Asking this more in hope than expectation.

I have tested your script on 7 different servers, zipping a single file. All the tests use identical code.

On 3 of them (all shared web hosting) your script works as expected.

On the other 4 I get this behaviour.

The script seems to work. The empty zip file is created, but although the zip.Add command is used and doesn't give any error, the zip archive remains empty.

The machines it doesn't work on are
Server 2016 / IIS 10
and
Server 2012 / IIS 8
but I only include that as background info, as the shared hosting is likely to be one of those too.

I'm at a loss as to why this would happen, but have also run out of any ways to diagnose it. Do you have any ideas?

As @OnnoPaap said in a previous issue, your script is becoming very important as the available zip components don't seem to be being updated to work on newer servers.

**Comment by OnnoPaap** [comment]
Oh oh.
I have it running on Windows Server 2008 and it will be upgraded soon. 
Good catch.

**Comment by GarveScott-Lodge** [comment]
I've no idea if that's the issue or if it's something else entirely.

**Comment by rcdmk** [comment]
Hi.
I have no clue, actually.
There must be something with permissions and thread model or impersonation.
I did a lot of tests with different settings for extraction and it always extracted empty folders, but for compression I never had an issue.

**Comment by AndryHTC** [comment]
@rcdmk the same in Server 2016. I try to add an entire folder (with a few files inside), but this never works... Always retrieve an empty ZIP... no files... no folder inside... only the ZIP with the given name and nothing else.

We really need it for several legacy Classic ASP projects

**Comment by gabbian0** [comment]
Any news about this? I'm experiencing the same problem.
Extract works well, but ADD results in an empty zip.
Using Windows Server 2019 with IIS 10

**Comment by rcdmk** [comment]
Actually the files are added and you can download the compressed file and check locally. What happens it that I couldn't find a way to setup the server and code to be able to extract files from a zip file using this approach. It is noted in the REAME as a known issue, BTW.

Does any of you have any idea on how to solve that? 
I tried to give the user full access and all permissions but that didn't work either, resulting in the same: empty folders being extracted.

**Comment by rjpedraza** [comment]
Same here. Cant add files. The zip file is empty. Can you help us Ricardo? Please. Tnk!!! :)

**Comment by rcdmk** [comment]
@rjpedraza, it has been a long time since I worked on this project, but on the last time I checked the script was able to compress files in the server, but extracting wasn't working (only extracts directory structure, not files).

Are you trying to extract contents of a file with this class?
If you download the file to your local computer, can you extract the contents with an application like 7zip or Winrar?

**Comment by GarveScott-Lodge** [comment]
Thanks to Ricardo for creating this script in the first case, but it seems likely you're not going to be able to update it to work on newer Windows servers. In case it's helpful to other people viewing this thread, the only working ZIP script or component I've been able to get to work on Windows Server 2012 and later is Chilkat, a paid suite of components. Hope you don't mind me posting that here R.

cheers

Garve

**Comment by rcdmk** [comment]
An update here after all those years. I was able to make version 0.4 work on Windows 11 Home, using IIS Express.
The compress and extract features are now working.

**Comment by rcdmk** [comment]
I'll close this issue with the hope that it is solved, but please feel free to reopen if the issue persists.
