### ISSUE TITLE
Problem on Windows2012r2

### ISSUE THREAD

**Issue by sdesalve** [rcdmk/aspZip#9]
Hi,

I'm struggling to solve a problem with your class.
On my developing's machine Windows 10 64bit your code is working like a charm! But same code on production's server Windows 2012 r2 64bit has a problem: files is not added to empty zip file.

```
curArquieve.Copyhere filepath, NoInterfaceYesToAll
``` 
don't add any file to empty zip file created.

Have you encountered this kind of problem?
Do you have any hint that can help me to solve this issue?

Thanks
SDeSalve

**Comment by rcdmk** [comment]
Hi,

That is usually caused by permission issues. Try checking if the IIS user has read-write access to the path.

Best,
Ricardo

**Comment by sdesalve** [comment]
I've allowed full control to IIS User on folder of zip file.

Also I've tried to run website impersonating and administrator account

**Comment by rcdmk** [comment]
Not sure if you are still on this, but I just released a new version that could solve this problem.

Version 0.4 was able to compress and extract files on Windows 11 Home with IIS Express.

**Comment by sdesalve** [comment]
Thanks. I will check!
